name: map_test
description: Flutter Map using Thunderforest API.
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_map: ^3.1.0
  geocoding_resolver: ^0.0.3+2
  geolocator: ^9.0.2
  georouter: ^0.0.1
  latlong2: ^0.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
